config/routes.rb
Oscarsapp::Application.routes.draw do

  resources :prizes do as_routes end
  resources :participants do as_routes end
  resources :choices do as_routes end
  resources :answers do as_routes end
  resources :questions do as_routes end
  resources :days do as_routes end
  resources :questions

  resources :days

  resources :users

  resources :participants
  
  resources :sessions, only: [:new, :create, :destroy]

  scope "api" do
    resources :questions
  end

  get '/mobile' => 'pages#mobile'

  get '/one/' => 'pages#one'
  get '/2/' => 'pages#2'
  get '/3/' => 'pages#3'
  get '/4/' => 'pages#4'
  get '/5/' => 'pages#5'
  get '/6/' => 'pages#6'
  get '/7/' => 'pages#7'
  get '/8/' => 'pages#8'
  get '/9/' => 'pages#9'
  get '/10/' => 'pages#10'
  get '/winner/' => 'pages#winner'
  get '/promotionend/' => 'pages#promotionend'

  get '/congrats/' => 'pages#congrats'

  get '/theend/' => 'pages#promotionend'

  get '/incorrect/' => 'pages#incorrect'

  get '/claim/' => 'pages#claim'

  get 'pages/home'

  match '/contest', :to => 'pages#contest', via: :get 
  match '/win', :to => 'pages#win', via: :get 
  match '/won', :to => 'pages#won', via: :get
  

  match 'pages/answer', via: :post 

  match '/signup', :to => 'users#new', via: :get 
  match '/signin', :to => 'sessions#new', via: :get
  match '/signout', :to => 'sessions#destroy', via: :delete

  match '/participate', :to => 'pages#participate', via: :post 

  root 'pages#home'

end

app/views/pages/1.html.erb
<%= stylesheet_link_tag  "layout", media: "all", "data-turbolinks-track" => true %>
<div class="container">
<img src="images/page_1/PAGE-1_01.jpg"  width="100%">
		
<img src="images/page_1/PAGE-1_02.jpg" width="100%" />

<div class="center">
<img class="derp1" height="36px" width="45.7%" src="images/page_1/PAGE-1_03.jpg" />
<img class="derp2" height="36px" width="8.35%" src="images/page_1/PAGE-1_04-idle.jpg" />
<img class="derp3" height="36px" width="45.9%" src="images/page_1/PAGE-1_05.jpg" />
</div>
<img class="derp4" width="100%" src="images/page_1/PAGE-1_06.jpg" />

<form class="fit" action="">
  
  <!-- Label and text input -->
  
  <input type="text" id="regularInput" placeholder="Enter Email Address..."/>
 
 
    <!-- Wrap each checkbox in a label, then give it the input and span for the text option -->
    <br />
    <label for="regularCheckbox">
      <input type="checkbox" id="regularCheckbox" value="checkbox 1" />
      <span class="white">I agree to terms and conditions</span>
    </label>
 	<br />
    <label for="secondRegularCheckbox">
      <input type="checkbox" id="secondRegularCheckbox" value="checkbox 2" />
      <span class="white">Sign up for our lame newsletter</span>
    </label>
 
 
</form>
</div>

app/views/pages/2.html.erb
<%= stylesheet_link_tag  "layout", media: "all", "data-turbolinks-track" => true %>
<div class="container">

<img src="images/level/LEVEL-2.jpg">

</div>

app/views/pages/4.html.erb
<%= stylesheet_link_tag  "layout", media: "all", "data-turbolinks-track" => true %>
<div class="container">

<img src="images/level/LEVEL-4.jpg">

</div>

app/views/pages/5.html.erb
<%= stylesheet_link_tag  "layout", media: "all", "data-turbolinks-track" => true %>
<div class="container">

<img src="images/level/LEVEL-5.jpg">

</div>

app/views/pages/6.html.erb
<%= stylesheet_link_tag  "layout", media: "all", "data-turbolinks-track" => true %>
<div class="container">

<img src="images/level/LEVEL-6.jpg">

</div>

app/views/pages/8.html.erb
<%= stylesheet_link_tag  "layout", media: "all", "data-turbolinks-track" => true %>
<div class="container">

<img src="images/level/LEVEL-8.jpg">

</div>

app/views/pages/9.html.erb
<%= stylesheet_link_tag  "layout", media: "all", "data-turbolinks-track" => true %>
<div class="container">

<img src="images/level/LEVEL-9.jpg">

</div>

app/views/pages/answer.html.erb
<%= @choice.choice %>

app/views/pages/claim.html.erb
<%= stylesheet_link_tag  "layout", media: "all", "data-turbolinks-track" => true %>
<div class="container">

<img src="images/winner/WINNER-PAGE.jpg">    


</div>

app/views/pages/home.html.erb
<%= stylesheet_link_tag  "layout", media: "all", "data-turbolinks-track" => true %>
<div class="container">
	
	
<%= session[:email] %>

	
<img src="images/page_1/MAIN-PAGE.jpg"  />
		


<div class="fit">


<%= form_for(:participant, :url => participate_path) do |f| %>  

  <!-- Label and text input -->
  
 	<%= f.text_field :email, size: 40, :placeholder => "Enter Email Address..." %>
 
    <!-- Wrap each checkbox in a label, then give it the input and span for the text option -->
    <br />
    <label for="regularCheckbox">
    <input type="checkbox" required>
      <span class="white">I agree to the terms and conditions</span>
      </input>
    </label>
 	<br />
    <label for="secondRegularCheckbox">
	  <%= f.check_box :subscribed %>
      <span class="white">Be Red Carpet-Ready - Sign me up for emails from Tadashi Shoji</span>
    </label>



    <%= submit_tag("", :class => "page1_submit") %>
 
<% end %>	

</div>
</div>

app/views/pages/incorrect.html.erb
<%= stylesheet_link_tag  "layout", media: "all", "data-turbolinks-track" => true %>
<div class="container">

<img src="/images/incorrect/WRONG-ANSWER.jpg" />


<div class="middleslices">


<div class="midright">
<%= link_to "", contest_path, :class => "play_again" %>
</div>

</div>









</div>

app/views/pages/mobile.html.erb
<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->
<head>

	<!-- Basic Page Needs
  ================================================== -->
	<meta charset="utf-8">
	<title>Your Page Title Here :)</title>
	<meta name="description" content="">
	<meta name="author" content="">

	<!-- Mobile Specific Metas
  ================================================== -->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

	<!-- CSS
  ================================================== -->

	<%= stylesheet_link_tag "base" %>
	<%= stylesheet_link_tag "skeleton" %>
	<%= stylesheet_link_tag "layout" %>
	<!--[if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->

	<!-- Favicons
	================================================== -->
	<link rel="shortcut icon" href="images/favicon.ico">
	<link rel="apple-touch-icon" href="images/apple-touch-icon.png">
	<link rel="apple-touch-icon" sizes="72x72" href="images/apple-touch-icon-72x72.png">
	<link rel="apple-touch-icon" sizes="114x114" href="images/apple-touch-icon-114x114.png">

</head>
<body>



	<!-- Primary Page Layout
	================================================== -->

	<!-- Delete everything in this .container and get started on your own site! -->

	<div class="container sixteen columns">
	
		

		<div class="sixteen columns">

			<img src="https://dl.dropboxusercontent.com/u/750532/1.jpg"></img>
	</div>

		<div class="one column">
			<span class="herotext">&nbsp;&nbsp;Finally, it's your turn to shine in the bright lights. Put your Oscars knowledge to the test with a walk down our virtual red carpet. Each correct answer will put you one step closer to making your elegant entrance into 
the grand ceremony. Answer all 10 questions correctly and win a special prize from Tadashi Shoji. </span>

<span class="herotext2">&nbsp;&nbsp;Feeling camera-ready? Step out of the limo and play A Red Carpet Affair.</span>
</div>

<form class="fit" action="">
  
  <!-- Label and text input -->
  
  <input type="text" id="regularInput" placeholder="Enter Email Address..."/>
 
 
    <!-- Wrap each checkbox in a label, then give it the input and span for the text option -->
    <label for="regularCheckbox">
      <input type="checkbox" id="regularCheckbox" value="checkbox 1" />
      <span class="white">I agree to terms and conditions</span>
    </label>
 
    <label for="secondRegularCheckbox">
      <input type="checkbox" id="secondRegularCheckbox" value="checkbox 2" />
      <span class="white">Sign up for our lame newsletter</span>
    </label>
  </fieldset>
 
 
</form>

<a href="#" target="_blank" id="shopnowimage"></a>


	</div><!-- container -->


<!-- End Document
================================================== -->
</body>
</html>

app/views/pages/promotionend.html.erb
<%= stylesheet_link_tag  "layout", media: "all", "data-turbolinks-track" => true %>
<div class="container">

<img src="images/promotionend/PROMOTION-HAS-ENDED_01.jpg"  width="100%">
		
<img src="images/promotionend/PROMOTION-HAS-ENDED_02.jpg" width="100%" />

<div class="center">
<img src="images/promotionend/PROMOTION-HAS-ENDED_03.jpg" width="100%" />
<img src="images/promotionend/PROMOTION-HAS-ENDED_04.jpg" width="100%" />
<img src="images/promotionend/PROMOTION-HAS-ENDED_05.jpg" width="100%" />

</div>
<img class="derp4" width="100%" src="images/promotionend/PROMOTION-HAS-ENDED_06.jpg" />
<img src="images/promotionend/PROMOTION-HAS-ENDED_07.jpg" width="100%" />

<form class="fit" action="">
  
  <!-- Label and text input -->
  
  <input type="text" id="regularInput" placeholder="Enter Email Address..."/>
 
 
    <!-- Wrap each checkbox in a label, then give it the input and span for the text option -->
    <br />
    <label for="regularCheckbox">
      <input type="checkbox" id="regularCheckbox" value="checkbox 1" />
      <span class="white">I agree to terms and conditions</span>
    </label>
 	<br />
    <label for="secondRegularCheckbox">
      <input type="checkbox" id="secondRegularCheckbox" value="checkbox 2" />
      <span class="white">Sign up for our lame newsletter</span>
    </label>

    <%= submit_tag %>
 
 
</form>
</div>

app/views/pages/winner.html.erb
<%= stylesheet_link_tag  "layout", media: "all", "data-turbolinks-track" => true %>
<div class="container">


<img src="images/winner/WINNER-LEVEL-10.jpg">    

<a href="/claim"><img class="claimprize" src="images/winner/CLAIM-PRIZE-BUTTON.png"></a>
	<img src="images/level/LEVEL-10.jpg">    

	<img src="images/winner/CLAIM-PRIZE-BUTTON.png">


	<h1>CONGRATULATIONS!!! YOU WON</h1>

	<h2><%= @prize.promocode %></h2>

</div>