config/routes.rb
Oscarsapp::Application.routes.draw do

  resources :prizes do as_routes end
  resources :participants do as_routes end
  resources :choices do as_routes end
  resources :answers do as_routes end
  resources :questions do as_routes end
  resources :days do as_routes end
  resources :questions

  resources :days

  resources :users

  resources :participants
  
  resources :sessions, only: [:new, :create, :destroy]

  scope "api" do
    resources :questions
  end

  get '/mobile' => 'pages#mobile'

  get '/one/' => 'pages#one'
  get '/2/' => 'pages#2'
  get '/3/' => 'pages#3'
  get '/4/' => 'pages#4'
  get '/5/' => 'pages#5'
  get '/6/' => 'pages#6'
  get '/7/' => 'pages#7'
  get '/8/' => 'pages#8'
  get '/9/' => 'pages#9'
  get '/10/' => 'pages#10'
  get '/winner/' => 'pages#winner'
  get '/promotionend/' => 'pages#promotionend'

  get '/congrats/' => 'pages#congrats'

  get '/theend/' => 'pages#promotionend'

  get '/incorrect/' => 'pages#incorrect'

  get '/claim/' => 'pages#claim'

  get 'pages/home'

  match '/contest', :to => 'pages#contest', via: :get 
  match '/win', :to => 'pages#win', via: :get 
  match '/won', :to => 'pages#won', via: :get
  

  match 'pages/answer', via: :post 

  match '/signup', :to => 'users#new', via: :get 
  match '/signin', :to => 'sessions#new', via: :get
  match '/signout', :to => 'sessions#destroy', via: :delete

  match '/participate', :to => 'pages#participate', via: :post 

  root 'pages#home'

end

app/views/layouts/_header.html.erb
<% if signed_in? %>
	<%= link_to "Sign out", signout_path, method: "delete" %>
	<%= link_to "Settings", edit_user_path(current_user)  %>
<% else %>
	<%#= link_to "Sign in", signin_path %>
<% end %>	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>A Red Carpet Affair | Tadashi Shoji</title>
  <%= stylesheet_link_tag    "layout", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    "days", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    "pages", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    "participants", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    "questions", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    "scaffolds", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    "active_scaffold", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    "bootstrap", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "bootstrap", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<%= render 'layouts/header' %>

	<%= yield %>

	<%= debug(params) if Rails.env.development? %>
	<%= debug(session[:participant_id]) if Rails.env.development? %>
	
</body>
</html>